// Map1_1.h  —  generated by Entitled Logic map editor

#pragma once

extern const unsigned short Map1_1[64][64];
extern const unsigned char Map1_1_Valid[64][64];
extern const unsigned short Map1_1_Deco[64][64];
extern const unsigned char Map1_1_Collision[64][64];
