// Map1_2_TileAssets.h  —  generated by Entitled Logic map editor
//
// Tile index → imported Unreal asset (UTexture2D). Index 0 = empty cell.
// Assets are expected at /Game/Tiles/  (on disk: <Project>/Content/Tiles/).
// Import the PNGs with the generated import_tiles_to_unreal.py script.
//
// Packaging note: string-path references are invisible to the cooker. Add
//   /Game/Tiles  under Project Settings → Packaging →
//   "Additional Asset Directories to Cook" so the tiles ship in packaged builds.
//
// Example:
//   const TCHAR* Path = Map1_2_TileAssets[Map1_2[x][y]];
//   UTexture2D* Tex = Path[0] ? LoadObject<UTexture2D>(nullptr, Path) : nullptr;

#pragma once

#include "CoreMinimal.h"

// inline (C++17+) → one definition shared across translation units.
inline const TCHAR* const Map1_2_TileAssets[] =
{
    TEXT(""),  // 0 = empty
    TEXT("/Game/Tiles/BrownDirt"),  // 1
    TEXT("/Game/Tiles/GrayStone"),  // 2
    TEXT("/Game/Tiles/GreenGrass"),  // 3
    TEXT("/Game/Tiles/tile_20260930_174923_435"),  // 4
    TEXT("/Game/Tiles/tile_20260930_174951_546"),  // 5
    TEXT("/Game/Tiles/tile_20260930_175006_445"),  // 6
    TEXT("/Game/Tiles/blend_00007_2e70ee5b"),  // 7
    TEXT("/Game/Tiles/blend_00008_d316c5f3"),  // 8
    TEXT("/Game/Tiles/blend_00009_ed5b2780"),  // 9
    TEXT("/Game/Tiles/blend_00010_6adad853"),  // 10
    TEXT("/Game/Tiles/blend_00011_6ae41cd3"),  // 11
    TEXT("/Game/Tiles/blend_00012_6c2df071"),  // 12
    TEXT("/Game/Tiles/blend_00013_78ee2621"),  // 13
    TEXT("/Game/Tiles/blend_00014_16ad34b1"),  // 14
    TEXT("/Game/Tiles/blend_00015_7e99afc1"),  // 15
    TEXT("/Game/Tiles/blend_00016_0f286171"),  // 16
    TEXT("/Game/Tiles/blend_00017_47552d41"),  // 17
    TEXT("/Game/Tiles/blend_00018_5dc3d151"),  // 18
    TEXT("/Game/Tiles/blend_00019_be042281"),  // 19
};

inline constexpr int32 Map1_2_TileAssetCount = 20;
