# ============================================================================
#  import_tiles_to_unreal.py
#  Auto-generated by EntitledLogicTileGen. Imports the tile PNGs that sit
#  next to this script into your Unreal project as pixel-art textures.
# ============================================================================
#
#  WHAT THIS DOES
#    - Imports every .png in SOURCE_DIR (set below) into the Unreal content
#      path DEST_PATH (default /Game/Tiles) as UTexture2D assets.
#    - Configures each one for crisp pixel art: nearest-neighbor filtering,
#      sRGB on, no mipmaps, uncompressed (TC_EDITOR_ICON).
#    - Saves the assets so they persist in your project.
#    These are the same tiles referenced by index in the generated
#    Map<level>_<variant>.cpp / .h, and by name in <base>_TileAssets.h.
#
#  PREREQUISITES (one-time)
#    1. Unreal Engine 5.7 with your project open.
#    2. Enable the Python plugin: Edit > Plugins > search 'Python Editor
#       Script Plugin' > tick Enabled > restart the editor.
#    3. (Recommended) Enable 'Editor Scripting Utilities' the same way.
#
#  HOW TO RUN (pick one)
#    A) Menu:  Tools > Execute Python Script...  then choose this file.
#    B) Output Log: open Window > Output Log, switch the command box
#       dropdown from 'Cmd' to 'Python', and run:
#           exec(open(r'FULL/PATH/TO/import_tiles_to_unreal.py').read())
#    C) Headless / command line:
#           UnrealEditor-Cmd.exe "C:/Path/MyProject.uproject" -run=pythonscript \
#               -script="C:/Path/import_tiles_to_unreal.py"
#
#  SOURCE_DIR and DEST_PATH below are already filled in for this export.
#    - SOURCE_DIR points at the folder these PNGs were written to. If you
#      move the PNGs, update SOURCE_DIR to match.
#    - DEST_PATH is an Unreal content path: '/Game/...' maps to your
#      project's Content/ folder on disk.  /Game/Tiles -> Content/Tiles.
#
#  RE-RUNNING
#    Safe to run again. replace_existing=True overwrites existing tiles of
#    the same name in place, so indices stay stable. New PNGs are added.
#
#  PACKAGING NOTE (important for cooked / shipping builds)
#    The map files reference tiles by string path, which the cooker cannot
#    see automatically. Add the tile directory to:
#        Project Settings > Packaging > Additional Asset Directories to Cook
#    and add  /Game/Tiles  so the textures ship with the build.
#
#  TROUBLESHOOTING
#    - 'name unreal is not defined'  -> Python plugin not enabled (see above),
#      or you ran it in 'Cmd' mode instead of 'Python' in the Output Log.
#    - 'SOURCE_DIR not found'        -> the PNGs moved; fix the path below.
#    - Tiles look blurry in-game     -> confirm the texture Filter is Nearest
#      and Mip Gen Settings is NoMipmaps (this script sets both).
# ============================================================================

import os
import unreal

SOURCE_DIR = r"C:\Users\apaxm\TileGenWorkspace\Tiles"
DEST_PATH  = "/Game/Tiles"

tools = unreal.AssetToolsHelpers.get_asset_tools()
tasks = []
for f in os.listdir(SOURCE_DIR):
    if not f.lower().endswith('.png'):
        continue
    t = unreal.AssetImportTask()
    t.set_editor_property('filename', os.path.join(SOURCE_DIR, f))
    t.set_editor_property('destination_path', DEST_PATH)
    t.set_editor_property('automated', True)
    t.set_editor_property('replace_existing', True)
    t.set_editor_property('save', True)
    tasks.append(t)

tools.import_asset_tasks(tasks)

# Configure each imported texture for crisp pixel art.
for t in tasks:
    for path in t.get_editor_property('imported_object_paths'):
        tex = unreal.load_asset(path)
        if isinstance(tex, unreal.Texture2D):
            tex.set_editor_property('srgb', True)
            tex.set_editor_property('filter', unreal.TextureFilter.TF_NEAREST)
            tex.set_editor_property('mip_gen_settings', unreal.TextureMipGenSettings.TMGS_NO_MIPMAPS)
            tex.set_editor_property('compression_settings', unreal.TextureCompressionSettings.TC_EDITOR_ICON)
            unreal.EditorAssetLibrary.save_asset(path)

unreal.log('Tile import complete.')
