// Map1_1_TileAssets.h  —  generated by Entitled Logic map editor
//
// Tile index → imported Unreal asset (UTexture2D). Index 0 = empty cell.
// Assets are expected at /Game/Tiles/  (on disk: <Project>/Content/Tiles/).
// Import the PNGs with the generated import_tiles_to_unreal.py script.
//
// Packaging note: string-path references are invisible to the cooker. Add
//   /Game/Tiles  under Project Settings → Packaging →
//   "Additional Asset Directories to Cook" so the tiles ship in packaged builds.
//
// Example:
//   const TCHAR* Path = Map1_1_TileAssets[Map1_1[x][y]];
//   UTexture2D* Tex = Path[0] ? LoadObject<UTexture2D>(nullptr, Path) : nullptr;

#pragma once

#include "CoreMinimal.h"

// inline (C++17+) → one definition shared across translation units.
inline const TCHAR* const Map1_1_TileAssets[] =
{
    TEXT(""),  // 0 = empty
    TEXT("/Game/Tiles/tile_20260930_174923_435"),  // 1
    TEXT("/Game/Tiles/tile_20260930_174951_546"),  // 2
    TEXT("/Game/Tiles/tile_20260930_175006_445"),  // 3
};

inline constexpr int32 Map1_1_TileAssetCount = 4;
