// Map1_2.h  —  generated by Entitled Logic map editor

#pragma once

extern const unsigned short Map1_2[64][64];
extern const unsigned char Map1_2_Valid[64][64];
extern const unsigned short Map1_2_Deco[64][64];
extern const unsigned char Map1_2_Collision[64][64];
